### ISSUE TITLE
Digital Signature Problem

### ISSUE THREAD

**Issue by lonnietc** [microsoft/Windows-rust-driver-samples#17]
Hello 

Everything seems to compile up just fine on my Windows 10 (x64) system but seem to run into a problem in Step 8 for "Install the Driver from the Admin Prompt"

```
D:\Win-rust-driver-samples\test\target\debug>pnputil.exe /add-driver echo_2.inf /install

Microsoft PnP Utility

Adding driver package:  echo_2.inf
Failed to add driver package: The third-party INF does not contain digital signature information.

Total driver packages:  1
Added driver packages:  0
```

It fails to add the driver with the as the INF does not contain digital signature information.

How  to correct this?

Thanks as I think that everything is very close to working, now.

**Comment by JohnAZoidberg** [comment]
You have to install the inf in `target\debug\echo_2_package\echo_2.inf`. One folder deeper.
