### ISSUE TITLE
driver not loaded

### ISSUE THREAD

**Issue by ruohki** [microsoft/Windows-rust-driver-samples#9]
Running a recent VM Ware Windows 11 VM to test the driver. Also using up-to-date SDKs.
I can build the driver and the sample application. I repeated all the steps mentioned in the repo. Yet, the driver doesn't seem to get loaded after installing it (which also installs it without any errors). What am I missing here? Since I am new to driver development, what else can I do to debug what's going on? Besides output from the installation and device creation stuff.

pnputil
```
PS C:\Users\guy\Desktop\New folder> pnputil.exe /add-driver .\echo_2.inf /install
Microsoft PnP Utility

Adding driver package:  echo_2.inf
Driver package added successfully.
Published Name:         oem8.inf
Driver package installed on device: SWD\DEVGEN\{5a3f9cb9-29c5-4349-badd-48ba5a0c1477}

Total driver packages:  1
Added driver packages:  1
```

devgen
```
PS C:\Users\guy\Desktop> .\devgen.exe /add /hardwareid "root\ECHO_2"
Microsoft Device Generator

Device successfully created. Device Instance ID: SWD\DEVGEN\{5a3f9cb9-29c5-4349-badd-48ba5a0c1477}
```

The test app only returns:
```
Error: "Error: No active device interfaces found.  Is the sample driver loaded?"
```

And yes i tried turning my pc off and on again multiple times :D

**Comment by harkness526** [comment]
I have the same problem
